version: 'latest'

services:
  postgres:
    container_name: test_dev
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=article 
    volumes:
      - ./data:/data/postgres
    ports:
      - 5432:5423